CREATE TABLE IF NOT EXISTS final_assessments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  class_id INT NOT NULL,
  subject_id INT NOT NULL,
  student_id INT NOT NULL,
  school_period_set_id INT NOT NULL,
  assessment_scope VARCHAR(16) NOT NULL,
  assessment_label VARCHAR(80) NOT NULL,
  school_year_label VARCHAR(32) NOT NULL,
  period_from DATE NOT NULL,
  period_to DATE NOT NULL,
  subject_is_schularbeit TINYINT(1) NULL,
  suggestion_value TINYINT NULL,
  suggestion_label VARCHAR(64) NULL,
  suggestion_explanation TEXT NULL,
  final_grade TINYINT NULL,
  deviation_flag TINYINT(1) NOT NULL DEFAULT 0,
  deviation_note TEXT NULL,
  teacher_comment TEXT NULL,
  data_basis_level VARCHAR(16) NOT NULL,
  data_basis_label VARCHAR(64) NOT NULL,
  data_basis_explanation VARCHAR(255) NULL,
  participation_count INT NOT NULL DEFAULT 0,
  documented_day_count INT NOT NULL DEFAULT 0,
  positive_count INT NOT NULL DEFAULT 0,
  neutral_count INT NOT NULL DEFAULT 0,
  negative_count INT NOT NULL DEFAULT 0,
  unrated_count INT NOT NULL DEFAULT 0,
  participation_quality_label VARCHAR(64) NULL,
  participation_quality_avg DECIMAL(5,2) NULL,
  top_criteria VARCHAR(255) NULL,
  comments_summary TEXT NULL,
  oral_count INT NOT NULL DEFAULT 0,
  oral_positive_count INT NOT NULL DEFAULT 0,
  oral_neutral_count INT NOT NULL DEFAULT 0,
  oral_negative_count INT NOT NULL DEFAULT 0,
  oral_summary_text VARCHAR(255) NULL,
  written_count INT NOT NULL DEFAULT 0,
  written_avg DECIMAL(5,2) NULL,
  written_summary_text VARCHAR(255) NULL,
  written_type_summary_json LONGTEXT NULL,
  semester_hint VARCHAR(255) NULL,
  year_trend_label VARCHAR(128) NULL,
  status ENUM('draft','final') NOT NULL DEFAULT 'draft',
  snapshot_json LONGTEXT NOT NULL,
  last_change_note TEXT NULL,
  created_by INT NOT NULL,
  updated_by INT NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  finalized_at DATETIME NULL,
  FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (school_period_set_id) REFERENCES school_period_sets(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_final_assessment_slot (class_id,subject_id,student_id,school_period_set_id,assessment_scope),
  INDEX idx_final_assessment_lookup (class_id,subject_id,school_period_set_id,assessment_scope,status),
  INDEX idx_final_assessment_student (student_id,school_period_set_id,assessment_scope)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS final_assessment_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  final_assessment_id INT NOT NULL,
  changed_by INT NOT NULL,
  change_type VARCHAR(24) NOT NULL,
  status_before VARCHAR(16) NULL,
  status_after VARCHAR(16) NOT NULL,
  final_grade_before TINYINT NULL,
  final_grade_after TINYINT NULL,
  change_note TEXT NULL,
  snapshot_json LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL,
  FOREIGN KEY (final_assessment_id) REFERENCES final_assessments(id) ON DELETE CASCADE,
  FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_final_assessment_history_lookup (final_assessment_id,created_at),
  INDEX idx_final_assessment_history_user (changed_by,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
