<?php
require_once __DIR__.'/auth.php';
require_once __DIR__.'/helpers.php';
require_once __DIR__.'/settings.php';
require_once __DIR__.'/version.php';
require_once __DIR__.'/security.php';

function _asset_v(string $path): string {
  $full = __DIR__ . '/../' . ltrim($path,'/');
  if (is_file($full)) return (string)filemtime($full);
  return '1';
}

function render_header(string $title, ?array $u=null): void {
  $bp = cfg()['base_path'] ?? '';
  $u  = $u ?? current_user();
  security_send_headers();
  include __DIR__.'/../partials/header.php';
}

function render_footer(): void {
  $bp = cfg()['base_path'] ?? '';
  include __DIR__.'/../partials/footer.php';
}

function dirty_form_attrs(bool $initial = false): string {
  $attrs = ['data-dirty-watch="1"'];
  if ($initial) $attrs[] = 'data-dirty-initial="1"';
  return implode(' ', $attrs);
}

function legal_hints_enabled(?array $u = null): bool {
  $u = $u ?? current_user();
  return ((string)($u['pref_legal_hints_enabled'] ?? '1') !== '0');
}

function compact_entry_forms_enabled(?array $u = null): bool {
  $u = $u ?? current_user();
  return ((string)($u['pref_compact_forms_enabled'] ?? '0') === '1');
}

function entry_contrast_mode(?array $u = null): string {
  $u = $u ?? current_user();
  return ((string)($u['pref_visual_contrast'] ?? 'normal') === 'high') ? 'high' : 'normal';
}

/** Main navigation style: 'text' (default), 'icon' (symbols only) or 'icon_text' (both). */
function nav_style_mode(?array $u = null): string {
  $u = $u ?? current_user();
  $mode = (string)($u['pref_nav_style'] ?? 'text');
  return in_array($mode, ['icon', 'icon_text'], true) ? $mode : 'text';
}

/**
 * Minimal inline stroke icons for the main navigation. Self-contained (no icon
 * font / external request) and inherit the surrounding text color via
 * `currentColor`, so they work in every theme/contrast combination unchanged.
 */
function nav_icon(string $key): string {
  $paths = [
    'dashboard'        => '<path d="M4 11.5 12 5l8 6.5"/><path d="M6 10.5V19a1 1 0 0 0 1 1h3v-5h4v5h3a1 1 0 0 0 1-1v-8.5"/>',
    'manage'           => '<rect x="4" y="4" width="7" height="7" rx="1.4"/><rect x="13" y="4" width="7" height="7" rx="1.4"/><rect x="4" y="13" width="7" height="7" rx="1.4"/><rect x="13" y="13" width="7" height="7" rx="1.4"/>',
    // Precise 8-tooth gear: vertices generated by rotating one tooth in exact
    // 45° steps around (12,12), so all teeth are mathematically identical and
    // evenly spaced (no hand-drawn asymmetry between the "teeth").
    'settings'         => '<path d="M 10.28 3.17 L 13.72 3.17 L 14.53 5.90 L 17.03 4.54 L 19.46 6.97 L 18.10 9.47 L 20.83 10.28 L 20.83 13.72 L 18.10 14.53 L 19.46 17.03 L 17.03 19.46 L 14.53 18.10 L 13.72 20.83 L 10.28 20.83 L 9.47 18.10 L 6.97 19.46 L 4.54 17.03 L 5.90 14.53 L 3.17 13.72 L 3.17 10.28 L 5.90 9.47 L 4.54 6.97 L 6.97 4.54 L 9.47 5.90 Z"/><circle cx="12" cy="12" r="3"/>',
    'reports'          => '<path d="M5 20V10"/><path d="M12 20V4"/><path d="M19 20v-7"/><path d="M3 20h18"/>',
    'final_assessment' => '<path d="m9 12 2 2 4-4"/><circle cx="12" cy="12" r="9"/>',
    'account'          => '<circle cx="12" cy="8" r="3.4"/><path d="M5 20a7 7 0 0 1 14 0"/>',
    'logout'           => '<path d="M9 5H6a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h3"/><path d="m14 8 4 4-4 4"/><path d="M18 12H9"/>',
    'login'            => '<path d="M15 19h3a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1h-3"/><path d="m10 8-4 4 4 4"/><path d="M15 12H6"/>',
  ];
  $p = $paths[$key] ?? '';
  if ($p === '') return '';
  return '<svg class="nav-icon" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">'.$p.'</svg>';
}

/**
 * Reorderable tiles on teacher/participation_new.php, in their default order.
 * Every one of them (including 'core', the Datum/Grund/Anlass/Eindruck
 * block) carries its own drag handle and can be freely repositioned; see
 * participation_tile_wrap() and participation_tile_drag_handle().
 * 'context' (Unterrichtskontext) includes "Kurze Beobachtung / Anlass" -
 * there used to be a separate 'note' tile for "Notiz (optional)", retired in
 * favour of that single free-text field. A teacher's saved order may still
 * contain the old key; participation_tile_order() silently drops it.
 */
function participation_tile_keys(): array {
  return ['hours','preset','core','performance','context','groups','criteria','students'];
}

/**
 * The teacher's saved tile order, validated against the known keys and
 * completed with any missing ones (appended at the end) so a stale or
 * partial saved value never hides a tile.
 */
function participation_tile_order(?array $u = null): array {
  $known = participation_tile_keys();
  $u = $u ?? current_user();
  $raw = (string)($u['pref_participation_tile_order'] ?? '');
  $saved = [];
  if ($raw !== '') {
    $decoded = json_decode($raw, true);
    if (is_array($decoded)) {
      foreach ($decoded as $key) {
        $key = (string)$key;
        if (in_array($key, $known, true) && !in_array($key, $saved, true)) $saved[] = $key;
      }
    }
  }
  foreach ($known as $key) {
    if (!in_array($key, $saved, true)) $saved[] = $key;
  }
  return $saved;
}

/**
 * The drag-handle icon itself (☰), meant to be printed as the first child of
 * a tile's own title element — a <legend> or an accordion <summary> — so it
 * sits visually INSIDE that tile's own border and stays visible even while
 * the tile is collapsed (a <summary> is never part of the collapsible
 * content). Shared by every reorderable tile on participation_new.php.
 */
function participation_tile_drag_handle(): string {
  return '<span class="tile-drag-handle" title="Ziehen, um die Reihenfolge zu ändern" aria-hidden="true">&#9776;</span>';
}

/**
 * Wraps a captured tile's HTML as one draggable unit. Purely structural — no
 * border/padding/margin of its own; the tile's own fieldset/accordion border
 * (with the handle already printed inside its legend/summary, see
 * participation_tile_drag_handle()) provides all the visible framing.
 * Returns '' unchanged for an empty tile (e.g. one hidden by the
 * simplified-entry preference), so no empty draggable shell is left behind.
 */
function participation_tile_wrap(string $key, string $html): string {
  if (trim($html) === '') return '';
  return '<div class="reorder-tile" draggable="true" data-tile-key="'.h($key).'">'.$html.'</div>';
}

function simplified_participation_entry_enabled(?array $u = null): bool {
  $u = $u ?? current_user();
  if (($u['role'] ?? '') !== 'teacher') return false;
  return ((string)($u['pref_simple_participation_entry'] ?? '0') === '1');
}

function teacher_school_context_label(?array $u = null): string {
  $u = $u ?? current_user();
  if (($u['role'] ?? '') !== 'teacher') return '';
  $teacherId = (int)($u['id'] ?? 0);
  if($teacherId <= 0) return '';

  static $cache = [];
  $selectedSchoolId=(int)($_SESSION['teacher_school_context_id'] ?? 0);
  $cacheKey=$teacherId.':'.$selectedSchoolId;
  if(isset($cache[$cacheKey])) return $cache[$cacheKey];

  try{
    if($selectedSchoolId>0){
      $st=db()->prepare("SELECT s.name
                         FROM teacher_schools ts
                         JOIN schools s ON s.id=ts.school_id
                         WHERE ts.teacher_id=? AND ts.school_id=? AND IFNULL(s.active,1)=1
                         LIMIT 1");
      $st->execute([$teacherId,$selectedSchoolId]);
      $selectedName=trim((string)($st->fetchColumn() ?: ''));
      if($selectedName !== ''){
        $cache[$cacheKey]=$selectedName;
        return $cache[$cacheKey];
      }

      // Legacy fallback: some existing installations derive school access
      // from class assignments until teacher_schools has been populated.
      $st=db()->prepare("SELECT DISTINCT s.name
                         FROM teacher_assignments ta
                         JOIN classes c ON c.id=ta.class_id
                         JOIN school_forms sf ON sf.id=c.school_form_id
                         JOIN schools s ON s.id=sf.school_id
                         WHERE ta.teacher_id=? AND sf.school_id=? AND IFNULL(s.active,1)=1
                         LIMIT 1");
      $st->execute([$teacherId,$selectedSchoolId]);
      $selectedName=trim((string)($st->fetchColumn() ?: ''));
      if($selectedName !== ''){
        $cache[$cacheKey]=$selectedName;
        return $cache[$cacheKey];
      }

      // Do not keep displaying a school that is no longer assigned.
      unset($_SESSION['teacher_school_context_id']);
    }

    $st = db()->prepare("SELECT DISTINCT s.name
                         FROM teacher_assignments ta
                         JOIN classes c ON c.id=ta.class_id
                         JOIN school_forms sf ON sf.id=c.school_form_id
                         JOIN schools s ON s.id=sf.school_id
                         WHERE ta.teacher_id=? AND IFNULL(s.active,1)=1
                         ORDER BY s.name");
    $st->execute([$teacherId]);
    $names = array_values(array_filter(array_map(static fn($row): string => trim((string)($row['name'] ?? '')), $st->fetchAll())));
    if(!$names){
      $fallback = db()->query("SELECT name FROM schools WHERE active=1 ORDER BY name LIMIT 1")->fetchColumn();
      if($fallback !== false) $names[] = trim((string)$fallback);
    }
    $cache[$cacheKey] = $names ? implode(' · ', array_unique($names)) : '';
  }catch(Throwable $e){
    $cache[$cacheKey] = '';
  }

  return $cache[$cacheKey];
}

function teacher_assignment_pairs(int $teacherId): array {
  static $cache = [];
  if (isset($cache[$teacherId])) return $cache[$teacherId];
  $st = db()->prepare("SELECT class_id, subject_id FROM teacher_assignments WHERE teacher_id=?");
  $st->execute([$teacherId]);
  $cache[$teacherId] = $st->fetchAll();
  return $cache[$teacherId];
}

function teacher_assignment_guard_attrs(?array $u = null, string $classField = 'class_id', string $subjectField = 'subject_id', string $message = 'Keine Berechtigung für diese Klasse/dieses Fach.'): string {
  $u = $u ?? current_user();
  if (($u['role'] ?? '') !== 'teacher') return '';
  $pairs = teacher_assignment_pairs((int)$u['id']);
  $encoded = [];
  foreach($pairs as $pair){
    $classId = (int)($pair['class_id'] ?? 0);
    $subjectId = (int)($pair['subject_id'] ?? 0);
    if($classId > 0 && $subjectId > 0) $encoded[] = $classId . ':' . $subjectId;
  }
  $encoded = array_values(array_unique($encoded));
  if(!$encoded) return '';
  return implode(' ', [
    'data-assignment-guard="1"',
    'data-class-field="'.h($classField).'"',
    'data-subject-field="'.h($subjectField).'"',
    'data-allowed-combos="'.h(implode(',', $encoded)).'"',
    'data-assignment-message="'.h($message).'"',
  ]);
}

function accordion_section_start(bool $enabled, string $title, bool $open = false, string $style = 'margin-top:12px', string $meta = '', string $class = '', string $dragHandle = ''): void {
  if(!$enabled) return;
  $classes = trim('accordion ' . $class);
  echo '<details class="'.h($classes).'"'.($open?' open':'').' style="'.h($style).'">';
  echo '<summary><span class="acc-title-group">'.$dragHandle.'<span class="acc-title">'.h($title).'</span></span>';
  if($meta!=='') echo '<span class="acc-meta">'.$meta.'</span>';
  echo '</summary><div class="acc-body">';
}

function accordion_section_end(bool $enabled): void {
  if($enabled) echo '</div></details>';
}
